<!-- content -->	
	<div class="row">
		<div class="col-md-12">
		
			<div class="row">
			
				<div class="col-xs-4">				
					<div class="stat-panel text-center">
						
						<div class="stat-row">
							<div class="stat-cell bg-dark-gray padding-sm text-xs text-semibold">
								<i class="fa fa-globe"></i>&nbsp;&nbsp;BANDWIDTH
							</div>
						</div>
						
						<div class="stat-row">
							<div class="stat-cell bordered no-border-t no-padding-hr">
								<div class="pie-chart" data-percent="43" id="easy-pie-chart-1">
									<div class="pie-chart-label">12.3TB</div>
								</div>
							</div>
						</div>
						
					</div>					
				</div>
				
				<div class="col-xs-4">
					<div class="stat-panel text-center">
					
						<div class="stat-row">
						
							<div class="stat-cell bg-dark-gray padding-sm text-xs text-semibold">
								<i class="fa fa-flash"></i>&nbsp;&nbsp;PICK LOAD
							</div>
						</div> 

						<div class="stat-row">
							<div class="stat-cell bordered no-border-t no-padding-hr">
								<div class="pie-chart" data-percent="93" id="easy-pie-chart-2">
									<div class="pie-chart-label">93%</div>
								</div>
							</div>
						</div>
						
					</div> 
				</div>
				
				<div class="col-xs-4">
					<div class="stat-panel text-center">
										
						<div class="stat-row">						
							<div class="stat-cell bg-dark-gray padding-sm text-xs text-semibold">
								<i class="fa fa-cloud"></i>&nbsp;&nbsp;USED RAM
							</div>
						</div>
						
						<div class="stat-row">
							<div class="stat-cell bordered no-border-t no-padding-hr">
								<div class="pie-chart" data-percent="75" id="easy-pie-chart-3">
									<div class="pie-chart-label">12GB</div>
								</div>
							</div>
						</div>
						
					</div> 
				</div>
			</div>
			
		</div>
	</div>
<!-- end content -->
