	
		
		

		<div id="content-container" style=" top: 20px;">
<!-- ========================================================================================================================== -->
			
			<div class="portlet">
				<div class="portlet-header">			
					<h3><i class="fa fa-user"></i>Información de la documentación de transito</h3>			
				</div> <!-- /.portlet-header -->

				<div class="portlet-content">			
		
					<div class="row">
						<div class="col-sm-12">
							<input type="text" id="inputEmail" class="form-control">
						</div>
					</div> <!-- /.row -->
		
					<div class="row">
						<div class="col-sm-5">
							<input type="text" placeholder=".col-sm-5" class="form-control">
						</div>
						<div class="col-sm-3">
							<input type="text" placeholder=".col-sm-3" class="form-control">
						</div>
						<div class="col-sm-4">
							<input type="text" placeholder=".col-sm-4" class="form-control">
						</div>
					</div> <!-- /.row -->
		
					<div class="row">
						<div class="col-sm-6">
							<input type="text" placeholder=".col-sm-4" class="form-control">
						</div>
						<div class="col-sm-6">
							<input type="text" placeholder=".col-sm-4" class="form-control">
						</div>
					</div> <!-- /.row -->
		
					<div class="row">
						<div class="col-sm-2">
							<input type="text" placeholder=".col-sm-2" class="form-control">
						</div>
						<div class="col-sm-2">
							<input type="text" placeholder=".col-sm-2" class="form-control">
						</div>
						<div class="col-sm-2">
							<input type="text" placeholder=".col-sm-2" class="form-control">
						</div>
						<div class="col-sm-2">
							<input type="text" placeholder=".col-sm-2" class="form-control">
						</div>
						<div class="col-sm-2">
							<input type="text" placeholder=".col-sm-2" class="form-control">
						</div>
						<div class="col-sm-2">
							<input type="text" placeholder=".col-sm-2" class="form-control">
						</div>
					</div> <!-- /.row -->
					
		
				</div> <!-- /.portlet-content -->

			</div>
			
<!-- ========================================================================================================================== -->		
		</div> <!-- /#content-container -->
		
		<div style="clear: both; color: #666;">
		.
		</div>
					
		
	