	
		
		

		<div id="content-container" style=" top: 20px;">
<!-- ========================================================================================================================== -->
		<form action="<?php echo BASE_URL.'modal/insertPlace';?>" method="post" id="formPlace" name="formPlace">	
			<div class="portlet">
				<div class="portlet-header">			
					<h3><i class="fa fa-map-marker"></i>Regisro de nuevo lugar de Nacimiento</h3>			
				</div> <!-- /.portlet-header -->
				
				
				<div class="portlet-content">			
				
					<div class="row">
					<div class="col-sm-8">
						<blockquote>
							La forma de registrar un nuevo lugar de nacimiento es escribiendo: <i><strong>"localidad, entidad federal"</strong></i> o <i><strong>"localidad, pais"</strong></i>.	
						</blockquote>
					</div>	
					</div>
					
					<input type="hidden" name="save" value="1">
					<div class="row">
						<div class="col-sm-12">
							<label>Lugar de Nacimiento</label>
							<input type="text" name="lugar" required="required" title="Este campo es Requerido" class="form-control" placeholder="localidad, entidad federal o pais">
						</div>
					</div> <!-- /.row -->
		
					<div class="row">
						<div class="col-sm-5">
							<input type="submit" class="btn btn-primary" value="Guardar" />
						</div>
					</div> <!-- /.row -->
		
				</div> <!-- /.portlet-content -->

			</div>
		</form>	
<!-- ========================================================================================================================== -->		
		</div> <!-- /#content-container -->
		
		<div style="clear: both; color: #666;">
		.
		</div>
					
		
	