	
		
		

		<div id="content-container" style=" top: 20px;">
<!-- ========================================================================================================================== -->
		<form action="<?php echo BASE_URL.'modal/insertBrand';?>" method="post" id="formBrand" name="formBrand">	
			<div class="portlet">
				<div class="portlet-header">			
					<h3><i class="fa fa-car"></i>Regisro de nueva marca de Auto</h3>			
				</div> <!-- /.portlet-header -->
				
				
				<div class="portlet-content">			
				
					<div class="row">
					<div class="col-sm-8">
						
					</div>	
					</div>
					
					<input type="hidden" name="save" value="1">
					<div class="row">
						<div class="col-sm-12">
							<label>Nueva Marca de Auto</label>
							<input type="text" 
									name="marca"
									id="marca" 
									required="required" 
									title="Este campo es Requerido" 
									class="form-control" 
									placeholder="Escriba la marca del auto"
							>
						</div>
					</div> <!-- /.row -->
		
					<div class="row">
						<div class="col-sm-5">
							<input type="submit" class="btn btn-primary" value="Guardar" />
						</div>
					</div> <!-- /.row -->
		
				</div> <!-- /.portlet-content -->

			</div>
		</form>	
<!-- ========================================================================================================================== -->		
		</div> <!-- /#content-container -->
		
		<div style="clear: both; color: #666;">
		.
		</div>
					
		
	