<!-- content -->	
	<div class="col-lg-9">

		<div class="page-header">
			<h2>Bienvenidos al Modulo de Personas</h2>
		</div>
		
		<h4>Subheading</h4>
		<p>Donec id elit non mi porta gravida at eget metus.</p>
	
		<h4>Subheading</h4>
		<p>Morbi leo risus, porta ac consectetur ac, vestibulum at eros.</p>
	
		<h4>Subheading</h4>
		<p>Maecenas sed diam eget risus varius blandit sit amet non magna.</p>
	</div>
	      
</div> <!-- este div es obligatorio -->
<!-- end content -->