<!-- content -->	
	<div class="col-lg-9">

		<div class="page-header">
			<h2>Registro de Persona</h2>
		</div>
		
		<form action="<?php echo BASE_URL;?>persons/insert" method="post">
			
			<div class="form-group">
    			<label>Cedula de identidad</label>
    			<input type="text" class="form-control" name="dni">
  			</div>
  			
  			<div class="form-group">
    			<label>Nombres</label>
    			<input type="text" class="form-control" name="name">
  			</div>
  			
  			<div class="form-group">
    			<label>Apellidos</label>
    			<input type="text" class="form-control" name="last_name">
  			</div>
  			
  			<button type="submit" class="btn btn-primary">Guardar</button>
		
		</form>
	<br>	
	</div>
	
	      
</div> <!-- este div es obligatorio -->
<!-- end content -->