<!-- content -->	
	<div class="col-lg-9">

		<div class="page-header">
			<h2>Registro de Persona</h2>
		</div>
		
		<form action="<?php echo BASE_URL;?>persons/update" method="post">
			
			<input type="hidden" name="id" value="<?php echo $this->registre['id']; ?>">
			
			<div class="form-group">
    			<label>Cedula de identidad</label>
    			<input type="text" class="form-control" name="dni" value="<?php echo $this->registre['dni']; ?>">
  			</div>
  			
  			<div class="form-group">
    			<label>Nombres</label>
    			<input type="text" class="form-control" name="name" value="<?php echo $this->registre['name']; ?>">
  			</div>
  			
  			<div class="form-group">
    			<label>Apellidos</label>
    			<input type="text" class="form-control" name="last_name" value="<?php echo $this->registre['last_name']; ?>">
  			</div>
  			
  			<button type="submit" class="btn btn-primary">Guardar</button>
		
		</form>
	<br>	
	</div>
	
	      
</div> <!-- este div es obligatorio -->
<!-- end content -->
