<!-- content -->	
	<div class="row">
		<div class="col-md-12">
		
			<form id="config_agencias" action="<?php echo BASE_URL.'config/agencias'; ?>" method="post" class="form-horizontal">

<!-- ================================== PANEL ================================== -->
				<div id="init">
				</div>			
				<div class="panel">
					<div class="panel-heading">
						<span class="panel-title">Insertar o Editar Agencias</span>
					</div>
				
					<div class="panel-body">
						<!-- ------------------------------------------------------------------------------------------- -->
						<div class="row clone">
							
							<input
								type="hidden"
								id="tpAction"
								name="tpAction"
								value="0"
							>
							
							<div class="col-sm-4">
								<div class="form-group no-margin-hr">
									<label><?php echo utf8_encode('Nombre de Agencia'); ?></label>
									<input 
										type="text" 
										class="form-control data" 
										id="nombre_ag" 
										name="nombre_ag"
									>
								</div>
							</div>
							
							<div class="col-sm-4">
								<div class="form-group no-margin-hr">
									<label><?php echo utf8_encode('identificador (iniciales)'); ?></label>
									<input 
										type="text" 
										class="form-control data2" 
										id="identificador" 
										name="identificador"
									>
								</div>
							</div>
													
							<div class="col-sm-2">
								<div class="form-group no-margin-hr" style="padding-top: 22px;">
									<button type="submit" class="form-control btn btn-primary">Guardar</button>
								</div>
							</div>
							
							<div class="col-sm-2">
								<div class="form-group no-margin-hr" style="padding-top: 22px;">
									<div class="form-control btn btn-danger" id="cancel">Cancelar</div>
								</div>
							</div>
							
						</div>
						<!-- ------------------------------------------------------------------------------------------- -->
						
					</div>
				
				</div>
			</form>	
<!-- ================================== PANEL ================================== -->
			<?php //App::varDump($this->data); ?>			
								
			<div class="panel">
				<div class="panel-heading">
					<span class="panel-title"><?php echo utf8_encode('<strong>Agencias</strong> registradas')?></span>
				</div>
				<div class="panel-body">
					
					<div class="table-primary">
						
						<?php if (isset($this->data)):?>
						<table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" id="tbTipoPers">
							<thead>
								<tr>
									<th>Codigo de registro (id)</th>
									<th>Nombre de Agencia</th>
									<th>identificador (iniciales)</th>
									<th>Acciones</th>
								</tr>
							</thead>
							
							<tbody>
							<?php for ($i = 0; $i < count($this->data); $i++):?>
								
								
								<tr class="gradeA">
									<td><?php echo $this->data[$i]['id']; ?></td>
									<td><?php echo $this->data[$i]['nombre_ag']; ?></td>
									<td><?php echo $this->data[$i]['identificador']; ?></td>
									
									<td style="text-align: center;">
										<button 
											class="btn btn-success btn-sm btn-action update" 
											id="<?php echo $this->data[$i]['id']; ?>"
											name="<?php echo $this->data[$i]['nombre_ag']; ?>"
											accesskey="<?php echo $this->data[$i]['identificador']; ?>"
										>
											<span class="fa fa-pencil"></span>
										</button>
									</td>
									
								</tr>
								
							<?php endfor;?>
							</tbody>
						</table>
						<?php else:?>
							<pre>No existen datos en esta Tabla</pre>
						<?php endif;?>
						
					</div>
					
				</div>
			</div>
				
<!-- ================================== PANEL ================================== -->
							
				
		
		
		</div>
	</div>
<!-- end content -->
