<!-- content -->	
	<div class="row">
		<div class="col-md-12">
		
			<form id="config_asignarConcepto" action="<?php echo BASE_URL.'config/asignarConcepto'; ?>" method="post" class="form-horizontal">

<!-- ================================== PANEL ================================== -->
				<div id="init">
				</div>			
				<div class="panel">
					<div class="panel-heading">
						<span class="panel-title"><?php echo utf8_encode('Insertar o Editar Precio de Polizas')?></span>
					</div>
				
					<div class="panel-body">
						
						<div class="well well-sm">
							<strong>
							<?php echo utf8_encode('Daños a Personas Víctimas del Accidente de Tránsito')?>
							</strong>
						</div>
						
						<div class="row">
							
							<div class="col-sm-4">
								<div class="form-group no-margin-hr">
									<label><?php echo utf8_encode('Gastos Médicos'); ?></label>
									<input 
										type="text" 
										class="form-control data" 
										id="gastosMedicos1" 
										name="gastosMedicos1"
									>
								</div>
							</div>
							
							
							<div class="col-sm-4">
								<div class="form-group no-margin-hr">
									<label><?php echo utf8_encode('Invalidez'); ?></label>
									<input 
										type="text" 
										class="form-control data" 
										id="invalidez1" 
										name="invalidez1"
									>
								</div>
							</div>
							
							
							<div class="col-sm-4">
								<div class="form-group no-margin-hr">
									<label><?php echo utf8_encode('Muerte'); ?></label>
									<input 
										type="text" 
										class="form-control data" 
										id="muerte1" 
										name="muerte1"
									>
								</div>
							</div>
							
						</div>
						<!-- ------------------------------------------------------------------------------------------- -->
						
						<div class="well well-sm">
							<strong>
							<?php echo utf8_encode('Daños a Personas Ocupantes del Vehículo Antes Descrito')?>
							</strong>
						</div>
						
						<div class="row">
							
							<div class="col-sm-4">
								<div class="form-group no-margin-hr">
									<label><?php echo utf8_encode('Gastos Médicos'); ?></label>
									<input 
										type="text" 
										class="form-control data" 
										id="gastosMedicos2" 
										name="gastosMedicos2"
									>
								</div>
							</div>
							
							
							<div class="col-sm-4">
								<div class="form-group no-margin-hr">
									<label><?php echo utf8_encode('Invalidez'); ?></label>
									<input 
										type="text" 
										class="form-control data" 
										id="invalidez2" 
										name="invalidez2"
									>
								</div>
							</div>
							
							
							<div class="col-sm-4">
								<div class="form-group no-margin-hr">
									<label><?php echo utf8_encode('Muerte'); ?></label>
									<input 
										type="text" 
										class="form-control data" 
										id="muerte2" 
										name="muerte2"
									>
								</div>
							</div>
							
						</div>
						<!-- ------------------------------------------------------------------------------------------- -->						
						
						<div class="well well-sm">
							<strong>
							<?php echo utf8_encode('Otros')?>
							</strong>
						</div>
						
						<div class="row">
							
							<div class="col-sm-4">
								<div class="form-group no-margin-hr">
									<label><?php echo utf8_encode('Daños a la Propiedad'); ?></label>
									<input 
										type="text" 
										class="form-control data" 
										id="daniosPropiedad" 
										name="daniosPropiedad"
									>
								</div>
							</div>
							
							
							<div class="col-sm-4">
								<div class="form-group no-margin-hr">
									<label><?php echo utf8_encode('Servicio de Grua'); ?></label>
									<input 
										type="text" 
										class="form-control data" 
										id="grua" 
										name="grua"
									>
								</div>
							</div>
							
							
							<div class="col-sm-4">
								<div class="form-group no-margin-hr">
									<label><?php echo utf8_encode('Estacionamiento'); ?></label>
									<input 
										type="text" 
										class="form-control data" 
										id="estacionamiento" 
										name="estacionamiento"
									>
								</div>
							</div>
							
						</div>
						<div class="row">
							
							<div class="col-sm-4">
								<div class="form-group no-margin-hr">
									<label><?php echo utf8_encode('Indemnización Semanal'); ?></label>
									<input 
										type="text" 
										class="form-control data" 
										id="indemnizacionSem" 
										name="indemnizacionSem"
									>
								</div>
							</div>
							
							
							<div class="col-sm-4">
								<div class="form-group no-margin-hr">
									<label><?php echo utf8_encode('Asistencia Legal'); ?></label>
									<input 
										type="text" 
										class="form-control data" 
										id="asistenciaLegal" 
										name="asistenciaLegal"
									>
								</div>
							</div>
							
							<div class="col-sm-4">
								<div class="form-group no-margin-hr" style="padding-top: 22px;">
									<button type="submit" class="form-control btn btn-primary">Guardar</button>
								</div>
							</div>
							
						</div>
						<!-- ------------------------------------------------------------------------------------------- -->
						<?php //App::varDump($this->cb); ?>	
						<div class="table-primary">
							
							<?php if (isset($this->cb)):?>
							<table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" id="np">
								<thead>
									<tr>
										<th><input type="checkbox" id="all"></th>
										<th><?php echo utf8_encode('Clase de vehiculo')?></th>
										<th><?php echo utf8_encode('Cobertura Asignada')?></th>
									</tr>
								</thead>
								
								<tbody>
								<?php for ($i = 0; $i < count($this->cb); $i++):?>
									
									
									<tr class="gradeA">
										
										<td><input type="checkbox" class="check" name="id[]" value="<?php echo $this->cb[$i]['id']; ?>"></td>
										<td><?php echo $this->cb[$i]['claseVehiculo']; ?></td>
										<td><?php echo number_format( $this->cb[$i]['cobertura'] ,2,",","."	) ; ?></td>
										
									</tr>
									
								<?php endfor;?>
								</tbody>
							</table>
							<?php else:?>
								<pre>No existen datos en esta Tabla</pre>
							<?php endif;?>
							
						</div>
					</form>
					</div>
				
				</div>
				
<!-- ================================== PANEL ================================== -->
					
								
			
			
				
<!-- ================================== PANEL ================================== -->
			
<!-- ================================== PANEL ================================== -->
			<?php //App::varDump($this->data); ?>			
								
			<div class="panel">
				<div class="panel-heading">
					<span class="panel-title"><?php echo utf8_encode('<strong>Conceptos</strong> de Polizas')?></span>
				</div>
				<div class="panel-body">
					
					<div class="table-primary">
						
						<?php if (isset($this->data)):?>
						<table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" id="tbTipoPers">
							<thead>
								<tr>
									<th><?php echo utf8_encode('C. de Vehículo')?></th>
									<th><?php echo utf8_encode('Cobertura')?></th>
									<th><?php echo utf8_encode('G.M (DPVAT)')?></th>
									<th><?php echo utf8_encode('Invalidez (DPVAT)')?></th>
									<th><?php echo utf8_encode('Muerte (DPVAT)')?></th>
									<th><?php echo utf8_encode('G.M (DPOVAD)')?></th>
									<th><?php echo utf8_encode('Invalidez (DPOVAD)')?></th>
									<th><?php echo utf8_encode('Muerte (DPOVAD)')?></th>
									<th><?php echo utf8_encode('Daños')?></th>
									<th><?php echo utf8_encode('Grua')?></th>
									<th><?php echo utf8_encode('Est. Sem.')?></th>
									<th><?php echo utf8_encode('Indemn.')?></th>
									<th><?php echo utf8_encode('Asesoria L.')?></th>
								</tr>
							</thead>
							
							<tbody>
							<?php for ($i = 0; $i < count($this->data); $i++):?>
								
								<tr class="gradeA">
									
									<td><?php echo $this->data[$i]['claseVehiculo']; ?></td>
									<td><?php echo number_format( $this->data[$i]['cobertura'],2,",","."); ?></td>
									<td><?php echo number_format( $this->data[$i]['gastosMedicos1'],2,",","."); ?></td>
									<td><?php echo number_format( $this->data[$i]['invalidez1'] ,2,",",".") ?></td>
									<td><?php echo number_format( $this->data[$i]['muerte1'] ,2,",",".") ?></td>
									<td><?php echo number_format( $this->data[$i]['gastosMedicos2'],2,",","."); ?></td>
									<td><?php echo number_format( $this->data[$i]['invalidez2'] ,2,",",".") ?></td>
									<td><?php echo number_format( $this->data[$i]['muerte2'] ,2,",",".") ?></td>
									<td><?php echo number_format( $this->data[$i]['daniosPropiedad'] ,2,",",".") ?></td>
									<td><?php echo number_format( $this->data[$i]['grua'] ,2,",",".") ?></td>
									<td><?php echo number_format( $this->data[$i]['estacionamiento'] ,2,",",".") ?></td>
									<td><?php echo number_format( $this->data[$i]['indemnizacionSem'] ,2,",",".") ?></td>
									<td><?php echo number_format( $this->data[$i]['asistenciaLegal'] ,2,",",".") ?></td>
									
								</tr>
								
							<?php endfor;?>
							</tbody>
						</table>
						<?php else:?>
							<pre>No existen datos en esta Tabla</pre>
						<?php endif;?>
						
					</div>
					
				</div>
			</div>
				
<!-- ================================== PANEL ================================== -->
							
				
		
		
		</div>
	</div>
<!-- end content -->
