<!-- content -->	
	<div class="row">
		<div class="col-md-12">
		
			<form id="config_precio" action="<?php echo BASE_URL.'config/asignarPrecio'; ?>" method="post" class="form-horizontal">

<!-- ================================== PANEL ================================== -->
				<div id="init">
				</div>			
				<div class="panel">
					<div class="panel-heading">
						<span class="panel-title"><?php echo utf8_encode('Insertar o Editar Precio de Polizas')?></span>
					</div>
				
					<div class="panel-body">
						
						<div class="row">
							<div class="col-sm-3">
								<div class="form-group no-margin-hr">
									<label><?php echo utf8_encode('Clase de Vehículo'); ?></label>
									<select 
										class="form-control"
										id="claseVehiculo" 
										name="claseVehiculo"
										table="claseVehiculo"										
									></select>
								</div>
							</div>
							
							<div class="col-sm-3">
								<div class="form-group no-margin-hr">
									<label><?php echo utf8_encode('Cobertura de la Poliza'); ?></label>
									<select 
										class="form-control"
										id="cobertura_id" 
										name="cobertura_id"
										table="cobertura"										
									></select>
								</div>
							</div>
							
							<div class="col-sm-3">
								<div class="form-group no-margin-hr">
									<label><?php echo utf8_encode('Precio de Poliza'); ?></label>
									<input 
										type="text" 
										class="form-control data" 
										id="precio" 
										name="precio"
									>
								</div>
							</div>
							
							<div class="col-sm-2">
								<div class="form-group no-margin-hr" style="padding-top: 22px;">
									<button type="submit" class="form-control btn btn-primary">Guardar</button>
								</div>
							</div>
							
						</div>
						<!-- ------------------------------------------------------------------------------------------- -->
						
						<div class="table-primary">
							
							<?php if (isset($this->np)):?>
							<table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" id="np">
								<thead>
									<tr>
										<th><input type="checkbox" id="all"></th>
										<th><?php echo utf8_encode('Clase de vehiculo')?></th>
										<th><?php echo utf8_encode('Tipo de Vehículo')?></th>
										<th><?php echo utf8_encode('Numero de Puesto')?></th>
									</tr>
								</thead>
								
								<tbody>
								<?php for ($i = 0; $i < count($this->np); $i++):?>
									
									
									<tr class="gradeA">
										
										<td><input type="checkbox" class="check" name="id[]" value="<?php echo $this->np[$i]['id']; ?>"></td>
										<td><?php echo $this->np[$i]['claseVehiculo']; ?></td>
										<td><?php echo $this->np[$i]['tipoVehiculo'] ; ?></td>
										<td><?php echo $this->np[$i]['numPuesto'] ; ?></td>
										
									</tr>
									
								<?php endfor;?>
								</tbody>
							</table>
							<?php else:?>
								<pre>No existen datos en esta Tabla</pre>
							<?php endif;?>
							
						</div>
					</form>
					</div>
				
				</div>
				
<!-- ================================== PANEL ================================== -->
			<?php //App::varDump($this->np); ?>			
								
			
			
				
<!-- ================================== PANEL ================================== -->
			
<!-- ================================== PANEL ================================== -->
			<?php //App::varDump($this->data); ?>			
								
			<div class="panel">
				<div class="panel-heading">
					<span class="panel-title"><?php echo utf8_encode('Contenido de la tabla <strong>Precios</strong>')?></span>
				</div>
				<div class="panel-body">
					
					<div class="table-primary">
						
						<?php if (isset($this->data)):?>
						<table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" id="tbTipoPers">
							<thead>
								<tr>
									<th><?php echo utf8_encode('Clase de Vehículo')?></th>
									<th><?php echo utf8_encode('Tipo de Vehículo')?></th>
									<th><?php echo utf8_encode('Numero de Puestos')?></th>
									<th><?php echo utf8_encode('Cobertura')?></th>
									<th><?php echo utf8_encode('Precio')?></th>
								</tr>
							</thead>
							
							<tbody>
							<?php for ($i = 0; $i < count($this->data); $i++):?>
								
								<tr class="gradeA">
									
									<td><?php echo $this->data[$i]['claseVehiculo']; ?></td>
									<td><?php echo $this->data[$i]['tipoVehiculo']; ?></td>
									<td><?php echo $this->data[$i]['numPuesto']; ?></td>
									<td><?php echo number_format( $this->data[$i]['cobertura'] ,2,",",".") ?></td>
									<td><?php echo number_format( $this->data[$i]['precio'] ,2,",",".") ?></td>
									
								</tr>
								
							<?php endfor;?>
							</tbody>
						</table>
						<?php else:?>
							<pre>No existen datos en esta Tabla</pre>
						<?php endif;?>
						
					</div>
					
				</div>
			</div>
				
<!-- ================================== PANEL ================================== -->
							
				
		
		
		</div>
	</div>
<!-- end content -->
