<!-- content -->	
	<div class="row">
		<div class="col-md-12">
		
			<form id="config_municipio" action="<?php echo BASE_URL.'config/actionDependence'; ?>" method="post" class="form-horizontal">

<!-- ================================== PANEL ================================== -->
				<div id="init">
				</div>			
				<div class="panel">
					<div class="panel-heading">
						<span class="panel-title"><?php echo utf8_encode('Insertar o Editar Municipio')?></span>
					</div>
				
					<div class="panel-body">
						<!-- ------------------------------------------------------------------------------------------- -->
						<div class="row clone">
							<input
								type="hidden"
								id="tpAction"
								name="tpAction"
								value="0"
							>
							<div class="col-sm-4">
								<div class="form-group no-margin-hr">
									<label><?php echo utf8_encode('Estado'); ?></label>
									<select 
										class="form-control"
										id="estado_id" 
										name="estado_id"
										table="estado"										
									><option value=""></option></select>
								</div>
							</div>
							
							<div class="col-sm-4">
								<div class="form-group no-margin-hr">
									<label><?php echo utf8_encode('Municipio'); ?></label>
									<input 
										type="text" 
										class="form-control data" 
										id="municipio" 
										name="municipio"
									>
								</div>
							</div>
													
							<div class="col-sm-2">
								<div class="form-group no-margin-hr" style="padding-top: 22px;">
									<button type="submit" class="form-control btn btn-primary">Guardar</button>
								</div>
							</div>
							
							<div class="col-sm-2">
								<div class="form-group no-margin-hr" style="padding-top: 22px;">
									<div class="form-control btn btn-danger" id="cancel">Cancelar</div>
								</div>
							</div>
							
						</div>
						<!-- ------------------------------------------------------------------------------------------- -->
						
					</div>
				
				</div>
			</form>	
<!-- ================================== PANEL ================================== -->
			<?php //App::varDump($this->data); ?>			
								
			<div class="panel">
				<div class="panel-heading">
					<span class="panel-title"><?php echo utf8_encode('Contenido de la tabla <strong>Tipo de Persona</strong>')?></span>
				</div>
				<div class="panel-body">
					
					<div class="table-primary">
						
						<?php if (isset($this->data)):?>
						<table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" id="tbTipoPers">
							<thead>
								<tr>
									<th>Codigo de registro (id)</th>
									<th><?php echo utf8_encode('Estado')?></th>
									<th><?php echo utf8_encode('Municipio')?></th>
									<th>Acciones</th>
								</tr>
							</thead>
							
							<tbody>
							<?php for ($i = 0; $i < count($this->data); $i++):?>
								
								
								<tr class="gradeA">
									<td><?php echo $this->data[$i]['0']; ?></td>
									<td><?php echo $this->data[$i]['estado']; ?></td>
									<td><?php echo $this->data[$i]['municipio']; ?></td>
									
									<td style="text-align: center;">
										<button 
											class="btn btn-success btn-sm btn-action update" 
											id="<?php echo $this->data[$i]['0']; ?>"
											select1="<?php echo $this->data[$i]['estado_id']; ?>"
											inputText="<?php echo $this->data[$i]['municipio']; ?>"
										>
											<span class="fa fa-pencil"></span>
										</button>
									</td>
									
								</tr>
								
							<?php endfor;?>
							</tbody>
						</table>
						<?php else:?>
							<pre>No existen datos en esta Tabla</pre>
						<?php endif;?>
						
					</div>
					
				</div>
			</div>
				
<!-- ================================== PANEL ================================== -->
							
				
		
		
		</div>
	</div>
<!-- end content -->
