<!-- content -->	
	<div class="row">
		<div class="col-md-12">
		
			<form id="config_usuarios" action="<?php echo BASE_URL.'config/usuarios'; ?>" method="post" class="form-horizontal">

<!-- ================================== PANEL ================================== -->
				<div id="init">
				</div>			
				<div class="panel">
					<div class="panel-heading">
						<span class="panel-title"><?php echo utf8_encode('Insertar o Editar Usuario')?></span>
					</div>
				
					<div class="panel-body">
						
						<div class="row">
							
							<div class="col-sm-4">
								<div class="form-group no-margin-hr">
									<label><?php echo utf8_encode('Nombre de usuario <span class="small">(para iniciar sessión)<span>'); ?></label>
									<input
										type="text" 
										class="form-control"
										id="nick" 
										name="nick"										
									>
								</div>
							</div>
							
							<div class="col-sm-4">
								<div class="form-group no-margin-hr">
									<label><?php echo utf8_encode('Clave de Usuario'); ?></label>
									<input
										type="password" 
										class="form-control"
										id="clave" 
										name="clave"										
									>
								</div>
							</div>							
							
							<div class="col-sm-4">
								<div class="form-group no-margin-hr">
									<label><?php echo utf8_encode('Repetir Clave de Usuario'); ?></label>
									<input
										type="password" 
										class="form-control"
										id="clave_eq" 
										name="clave_eq"										
									>
								</div>
							</div>
							
						</div>						
						<div class="row">
							
							<div class="col-sm-3">
								<div class="form-group no-margin-hr">
									<label><?php echo utf8_encode('Nombres'); ?></label>
									<input
										type="text" 
										class="form-control"
										id="nombre" 
										name="nombre"
										placeholder="Nombre e inicial del segundo"										
									>
								</div>
							</div>
							
							<div class="col-sm-3">
								<div class="form-group no-margin-hr">
									<label><?php echo utf8_encode('Apellidos'); ?></label>
									<input
										type="text" 
										class="form-control"
										id="apellido" 
										name="apellido"
										placeholder="Apellido e inicial del segundo"											
									>
								</div>
							</div>
							
							<div class="col-sm-3">
								<div class="form-group no-margin-hr">
									<label><?php echo utf8_encode('Tipo de Usuario'); ?></label>
									<select 
										class="form-control"
										id="perfilUsuario_id" 
										name="perfilUsuario_id"
										table="perfilUsuario"										
									></select>
								</div>
							</div>
							
							<div class="col-sm-3">
								<div class="form-group no-margin-hr">
									<label><?php echo utf8_encode('Agencia'); ?></label>
									<select 
										class="form-control"
										id="agencias_id" 
										name="agencias_id"
										table="agencias"										
									></select>
								</div>
							</div>
						
						</div>						
						<div class="row">
						
							<div class="col-sm-4">
								<div class="form-group no-margin-hr">
									<label><?php echo utf8_encode('Pregunta de Seguridad'); ?></label>
									<select 
										class="form-control"
										id="pregunta_id" 
										name="pregunta_id"
										table="pregunta"										
									></select>
								</div>
							</div>
							
							<div class="col-sm-4">
								<div class="form-group no-margin-hr">
									<label><?php echo utf8_encode('Respuesta de seguridad'); ?></label>
									<input
										type="password" 
										class="form-control"
										id="respuesta" 
										name="respuesta"										
									>
								</div>
							</div>
							
							<div class="col-sm-4">
								<div class="form-group no-margin-hr">
									<label><?php echo utf8_encode('Estatus Usuarios'); ?></label>
									<select 
										class="form-control"
										id="statusUsuarios_id" 
										name="statusUsuarios_id"
										table="statusUsuarios"
										disabled="disabled"										
									></select>
								</div>
							</div>	
							
						</div>						
						<div class="row">
						
							<div class="col-sm-2">
								<div class="form-group no-margin-hr" style="padding-top: 22px;">
									<button type="submit" class="form-control btn btn-primary">Guardar</button>
								</div>
							</div>
							
							<div class="col-sm-2">
								<div class="form-group no-margin-hr" style="padding-top: 22px;">
									<div class="form-control btn btn-danger" id="cancel">Cancelar</div>
								</div>
							</div>					
						
						</div>
						<!-- ------------------------------------------------------------------------------------------- -->
						<input
							type="hidden"
							id="tpAction"
							name="tpAction"
							value="0"
						>
						
					</div>
				
				</div>
			</form>	
<!-- ================================== PANEL ================================== -->
			<?php //App::varDump($this->data); ?>			
								
			<div class="panel">
				<div class="panel-heading">
					<span class="panel-title"><?php echo utf8_encode('Lista de <strong>Usuarios</strong>')?></span>
				</div>
				<div class="panel-body">
					
					<div class="table-primary">
						
						<?php if (isset($this->data)):?>
						<table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" id="tbTipoPers">
							<thead>
								<tr>
									<th>#</th>
									<th><?php echo utf8_encode('Nombre')?></th>
									<th><?php echo utf8_encode('Apellido')?></th>
									<th><?php echo utf8_encode('Nombre de Usuario')?></th>
									<th><?php echo utf8_encode('Agencia')?></th>
									<th><?php echo utf8_encode('Perfil de Usuario')?></th>
									<th><?php echo utf8_encode('Estatus Usuarios')?></th>
									<th>Acciones</th>
								</tr>
							</thead>
							
							<tbody>
							<?php for ($i = 0; $i < count($this->data); $i++):?>
								
								
								<tr class="gradeA">
									<td><?php echo $this->data[$i]['0']; ?></td>
									<td><?php echo $this->data[$i]['nombre']; ?></td>
									<td><?php echo $this->data[$i]['apellido']; ?></td>
									<td><?php echo $this->data[$i]['nick']; ?></td>
									<td><?php echo $this->data[$i]['nombre_ag']; ?></td>
									<td><?php echo $this->data[$i]['perfilUsuario']; ?></td>
									<td><?php echo $this->data[$i]['statusUsuarios']; ?></td>
									
									<td style="text-align: center;">
										<button 
											class="btn btn-success btn-sm btn-action update" 
											id="<?php echo $this->data[$i]['0']; ?>"
											url="<?php echo BASE_URL; ?>config/getRegistro"
										>
											<span class="fa fa-pencil"></span>
										</button>
										
									</td>
									
								</tr>
								
							<?php endfor;?>
							</tbody>
						</table>
						<?php else:?>
							<pre>No existen datos en esta Tabla</pre>
						<?php endif;?>
						
					</div>
					
				</div>
			</div>
				
<!-- ================================== PANEL ================================== -->
							
				
		
		
		</div>
	</div>
<!-- end content -->
