<!-- content -->	
	<div class="row">
		<div class="col-md-12">
			
			<div class="panel">
					<div class="panel-heading">
						<span class="panel-title"><?php echo utf8_encode('Factura de Impresión')?></span>
					</div>
					<?php //App::varDump(Session::get('data')); ?>
					<div class="panel-body"><?php /*Session::destroy('contadorImp');*/  ?>
						<!-- ------------------------------------------------------------------------------------------- -->
						<div class="row">
											
							<div class="col-sm-12">
								<div class="form-group no-margin-hr">
									<div id="pdf"></div>										
									<div id="disableSelect"></div>
								</div>
							</div><!-- col-sm-6 -->
						</div>
						
						<div class="row">
											
							<div class="col-sm-12">
								<div class="well well-sm">
									<?php echo utf8_encode('Código de Planilla Asignado al Contrato: ')?>
									<strong>
									<?php echo $this->codFact[0]['codigo'];?>
									</strong>									
								</div>
							</div>
						</div>
						
						<div class="row">
							<div class="col-sm-4">
								<?php //Session::destroy('printbtn');?>
								<?php $disabled = (Session::get('printbtn') == true) ? "disabled":"";?>
									
								<div class="form-group no-margin-hr">
									<button id="printbtn" class="btn btn-success" >
										<i class="fa fa-print"></i> 
										Imprimir
									</button>									
								</div>
								
							</div>
							
						</div>
						<?php $hideForm = (Session::get('printbtn') == true) ? "":"hideForm";?>
						
						<form id="adviser_impFact" action="<?php echo BASE_URL; ?>adviser/impFact" method="post">
						
							<div id="<?php echo $hideForm?>">
							<div class="row">												
								<div class="col-sm-12">
									<div class="form-group no-margin-hr">
										<h4><?php echo utf8_encode('Seleccione el resultado del proceso de impresión:')?></h4>
									</div>
								</div>							
							</div>
							
							<div class="row">
								<div class="col-sm-8">
									<div class="form-group no-margin-hr">
										<div class="radio" style="margin-top: 0;">
											<label>
												<input type="radio" name="resulImp2" id="" value="1" class="px">
												<span class="lbl"><?php echo utf8_encode('Proceso realizado con éxito!')?></span>
											</label>
										</div>
										<div class="radio" style="margin-top: 0;">
											<label>
												<input type="radio" name="resulImp2" id="" value="2" class="px">
												<span class="lbl"><?php echo utf8_encode('Durante la impresión, se dañó la planilla')?></span>
											</label>
										</div>
										<div class="radio" style="margin-top: 0;">
											<label>
												<input type="radio" name="resulImp2" id="" value="3" class="px">
												<span class="lbl"><?php echo utf8_encode('Se envió la solicitud de impresión, pero la impresora nunca imprimió')?></span>
											</label>
										</div>
										<div class="radio" style="margin-top: 0;">
											<label>
												<input type="radio" name="resulImp2" id="" value="4" class="px">
												<span class="lbl"><?php echo utf8_encode('Cancelé la impresion sin intención')?></span>
											</label>
										</div>
										
										
									</div>
								</div>
								<div class="col-sm-8">
									<div class="form-group no-margin-hr">
										<button type="submit" id="submitForm" class="btn btn-success">
											<i id="fback" class="fa fa-chevron-right"></i> 
											<?php echo utf8_encode('Siguiente')?>
										</button>
									</div>
								</div>
							</div>
							</div>
						</form>
					</div>
			</div>
			
			
				
			
				
				
			
		</div>
	</div>
<!-- end content -->
