<!-- content -->	
	<div class="row">
		<div class="col-md-12">
		
			<form id="adviser_renovarContrato" action="<?php echo BASE_URL.'adviser/renovarContrato'; ?>" method="post" class="form-horizontal">

<!-- ================================== PANEL ================================== -->
				<div id="init">
				</div>			
				<div class="panel">
					<div class="panel-heading">
						<span class="panel-title"><?php echo utf8_encode('Tabla de Clientes con Contratos Vencidos')?></span>
					</div>
				
					<div class="panel-body">
						<?php //App::varDump($this->data)?>
						<div class="table-primary">
							
							<?php if (isset($this->data)):?>
							<table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" id="np">
								<thead>
									<tr>
										<th><?php echo utf8_encode('<i class="fa fa-check-circle-o"></i>')?></th>
										<th><?php echo utf8_encode('Cedula')?></th>
										<th><?php echo utf8_encode('Nombre y Apellido')?></th>
										<th><?php echo utf8_encode('Marca')?></th>
										<th><?php echo utf8_encode('Modelo')?></th>
										<th><?php echo utf8_encode('Año')?></th>
										<th><?php echo utf8_encode('Fecha de vencimiento')?></th>
										<th><?php echo utf8_encode('Cobertura')?></th>
										<th><?php echo utf8_encode('Precio')?></th>
									</tr>
								</thead>
								
								<tbody>
								<?php for ($i = 0; $i < count($this->data); $i++):?>
									
									
									<tr class="gradeA">
										
										<td>
											<div class="radio" style="margin-top: 0;">
												<label>
													<input type="radio" name="idContrato" id="" value="<?php echo $this->data[$i]['id']; ?>" class="px">
													<span class="lbl"><?php echo utf8_encode('.')?></span>													
												</label>
											</div>
										</td>
										<td><?php echo $this->data[$i]['dni']; ?></td>
										<td><?php echo $this->data[$i]['nombres'].', '.$this->data[$i]['apellidos'] ; ?></td>
										<td><?php echo $this->data[$i]['marca'] ; ?></td>
										<td><?php echo $this->data[$i]['modelo'] ; ?></td>
										<td><?php echo $this->data[$i]['anio'] ; ?></td>
										<td><?php echo App::showDate( $this->data[$i]['fecha_ven'] ); ?></td>
										<td><?php echo $this->data[$i]['cobertura'] ; ?></td>
										<td><?php echo $this->data[$i]['precio'] ; ?></td>
										
									</tr>
									
								<?php endfor;?>
								</tbody>
							</table>
							<?php else:?>
								<pre>No existen datos en esta Tabla</pre>
							<?php endif;?>
							
						</div>
					
						<div class="col-sm-8">
							<div class="form-group no-margin-hr">
								<button type="submit" id="submitForm" class="btn btn-success">
									<i id="fback" class="fa fa-chevron-right"></i> 
									<?php echo utf8_encode('Seguiente')?>
								</button>
							</div>
						</div>
					
						
					</form>
					</div>
				
				</div>
				
<!-- ================================== PANEL ================================== -->
				
		
		
		</div>
	</div>
<!-- end content -->
