<!-- content -->	
	<div class="row">
		<div class="col-md-12">
			
			<div class="panel">
					<div class="panel-heading">
						<span class="panel-title"><?php echo utf8_encode('Relacion de Ventas')?></span>
					</div>
					
					<div class="panel-body">
						<!-- ------------------------------------------------------------------------------------------- -->
						<div class="row">
											
							<div class="col-sm-12">
								<div class="form-group no-margin-hr">
									<div id="pdf"></div>										
									<div id="disableSelect"></div>
								</div>
							</div><!-- col-sm-6 -->
						</div>
						
						
						<div class="row">
							<div class="col-sm-4">
									
								<div class="form-group no-margin-hr">
									<button id="printbtn" class="btn btn-success" >
										<i class="fa fa-print"></i> 
										Imprimir
									</button>
								</div>
								
							</div>
							
						</div>
						
					</div>
			</div>
			
			
				
			
				
				
			
		</div>
	</div>
<!-- end content -->
