-- MySQL Script generated by MySQL Workbench
-- 11/28/14 23:39:37
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema rcv_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `rcv_db` ;

-- -----------------------------------------------------
-- Schema rcv_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `rcv_db` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `rcv_db` ;

-- -----------------------------------------------------
-- Table `rcv_db`.`claseVehiculo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rcv_db`.`claseVehiculo` ;

CREATE TABLE IF NOT EXISTS `rcv_db`.`claseVehiculo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `clase` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rcv_db`.`tipoVehiculo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rcv_db`.`tipoVehiculo` ;

CREATE TABLE IF NOT EXISTS `rcv_db`.`tipoVehiculo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tpVehiculo` VARCHAR(60) NOT NULL,
  `claseVehiculo_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tipoV_claseVehiculo1_idx` (`claseVehiculo_id` ASC),
  CONSTRAINT `fk_tipoV_claseVehiculo1`
    FOREIGN KEY (`claseVehiculo_id`)
    REFERENCES `rcv_db`.`claseVehiculo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rcv_db`.`numPuesto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rcv_db`.`numPuesto` ;

CREATE TABLE IF NOT EXISTS `rcv_db`.`numPuesto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `numero` INT NOT NULL,
  `tipoVehiculo_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_numPuesto_tipoVehiculo1_idx` (`tipoVehiculo_id` ASC),
  CONSTRAINT `fk_numPuesto_tipoVehiculo1`
    FOREIGN KEY (`tipoVehiculo_id`)
    REFERENCES `rcv_db`.`tipoVehiculo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rcv_db`.`coberturas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rcv_db`.`coberturas` ;

CREATE TABLE IF NOT EXISTS `rcv_db`.`coberturas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cobertura` VARCHAR(80) NOT NULL,
  `claseVehiculo_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_coberturas_claseVehiculo1_idx` (`claseVehiculo_id` ASC),
  CONSTRAINT `fk_coberturas_claseVehiculo1`
    FOREIGN KEY (`claseVehiculo_id`)
    REFERENCES `rcv_db`.`claseVehiculo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rcv_db`.`precios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rcv_db`.`precios` ;

CREATE TABLE IF NOT EXISTS `rcv_db`.`precios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `precio` DECIMAL(6,2) NOT NULL,
  `coberturas_id` INT NOT NULL,
  `numPuesto_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_costoCob_coberturas1_idx` (`coberturas_id` ASC),
  INDEX `fk_costoCob_numPuesto1_idx` (`numPuesto_id` ASC),
  CONSTRAINT `fk_costoCob_coberturas1`
    FOREIGN KEY (`coberturas_id`)
    REFERENCES `rcv_db`.`coberturas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_costoCob_numPuesto1`
    FOREIGN KEY (`numPuesto_id`)
    REFERENCES `rcv_db`.`numPuesto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rcv_db`.`tpPersona`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rcv_db`.`tpPersona` ;

CREATE TABLE IF NOT EXISTS `rcv_db`.`tpPersona` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tpPersona` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rcv_db`.`estados`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rcv_db`.`estados` ;

CREATE TABLE IF NOT EXISTS `rcv_db`.`estados` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `estado` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rcv_db`.`municipios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rcv_db`.`municipios` ;

CREATE TABLE IF NOT EXISTS `rcv_db`.`municipios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `municipio` VARCHAR(80) NOT NULL,
  `estados_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_municipios_estados1_idx` (`estados_id` ASC),
  CONSTRAINT `fk_municipios_estados1`
    FOREIGN KEY (`estados_id`)
    REFERENCES `rcv_db`.`estados` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rcv_db`.`parroquias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rcv_db`.`parroquias` ;

CREATE TABLE IF NOT EXISTS `rcv_db`.`parroquias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `parroquia` VARCHAR(80) NOT NULL,
  `municipios_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_parroquias_municipios1_idx` (`municipios_id` ASC),
  CONSTRAINT `fk_parroquias_municipios1`
    FOREIGN KEY (`municipios_id`)
    REFERENCES `rcv_db`.`municipios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rcv_db`.`titulares`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rcv_db`.`titulares` ;

CREATE TABLE IF NOT EXISTS `rcv_db`.`titulares` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tpPersona_id` INT NOT NULL,
  `dni` VARCHAR(45) NOT NULL,
  `nombres` VARCHAR(60) NOT NULL,
  `apellidos` VARCHAR(60) NOT NULL,
  `parroquias_id` INT NOT NULL,
  `direccion` LONGTEXT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_titulares_tpPersona1_idx` (`tpPersona_id` ASC),
  INDEX `fk_titulares_parroquias1_idx` (`parroquias_id` ASC),
  CONSTRAINT `fk_titulares_tpPersona1`
    FOREIGN KEY (`tpPersona_id`)
    REFERENCES `rcv_db`.`tpPersona` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_titulares_parroquias1`
    FOREIGN KEY (`parroquias_id`)
    REFERENCES `rcv_db`.`parroquias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rcv_db`.`marcas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rcv_db`.`marcas` ;

CREATE TABLE IF NOT EXISTS `rcv_db`.`marcas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `marca` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rcv_db`.`modelos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rcv_db`.`modelos` ;

CREATE TABLE IF NOT EXISTS `rcv_db`.`modelos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `modelo` VARCHAR(100) NOT NULL,
  `marcas_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_modelos_marcas1_idx` (`marcas_id` ASC),
  CONSTRAINT `fk_modelos_marcas1`
    FOREIGN KEY (`marcas_id`)
    REFERENCES `rcv_db`.`marcas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rcv_db`.`usoVehiculo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rcv_db`.`usoVehiculo` ;

CREATE TABLE IF NOT EXISTS `rcv_db`.`usoVehiculo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uso` VARCHAR(45) NOT NULL,
  `claseVehiculo_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_usoVehiculo_claseVehiculo1_idx` (`claseVehiculo_id` ASC),
  CONSTRAINT `fk_usoVehiculo_claseVehiculo1`
    FOREIGN KEY (`claseVehiculo_id`)
    REFERENCES `rcv_db`.`claseVehiculo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rcv_db`.`statusCont`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rcv_db`.`statusCont` ;

CREATE TABLE IF NOT EXISTS `rcv_db`.`statusCont` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rcv_db`.`trans`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rcv_db`.`trans` ;

CREATE TABLE IF NOT EXISTS `rcv_db`.`trans` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `trans` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rcv_db`.`tpPago`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rcv_db`.`tpPago` ;

CREATE TABLE IF NOT EXISTS `rcv_db`.`tpPago` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tpPago` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rcv_db`.`agencias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rcv_db`.`agencias` ;

CREATE TABLE IF NOT EXISTS `rcv_db`.`agencias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre_ag` VARCHAR(60) NOT NULL,
  `identificador` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rcv_db`.`stFormatos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rcv_db`.`stFormatos` ;

CREATE TABLE IF NOT EXISTS `rcv_db`.`stFormatos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rcv_db`.`planillas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rcv_db`.`planillas` ;

CREATE TABLE IF NOT EXISTS `rcv_db`.`planillas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(45) NOT NULL,
  `agencias_id` INT NOT NULL,
  `stFormatos_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_planillas_agencias2_idx` (`agencias_id` ASC),
  INDEX `fk_planillas_stFormatos1_idx` (`stFormatos_id` ASC),
  CONSTRAINT `fk_planillas_agencias2`
    FOREIGN KEY (`agencias_id`)
    REFERENCES `rcv_db`.`agencias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_planillas_stFormatos1`
    FOREIGN KEY (`stFormatos_id`)
    REFERENCES `rcv_db`.`stFormatos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rcv_db`.`contratos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rcv_db`.`contratos` ;

CREATE TABLE IF NOT EXISTS `rcv_db`.`contratos` (
  `id` INT NOT NULL,
  `modelos_id` INT NOT NULL,
  `placa` VARCHAR(45) NOT NULL,
  `anio` YEAR NOT NULL,
  `color` VARCHAR(45) NOT NULL,
  `serial_c` VARCHAR(45) NOT NULL,
  `serial_m` VARCHAR(45) NOT NULL,
  `usoVehiculo_id` INT NOT NULL,
  `peso` VARCHAR(45) NOT NULL,
  `trans_id` INT NOT NULL,
  `statusCont_id` INT NOT NULL,
  `fecha_exp` DATE NOT NULL,
  `fecha_ven` DATE NOT NULL,
  `titulares_id` INT NOT NULL,
  `precios_id` INT NOT NULL,
  `tpPago_id` INT NOT NULL,
  `planillas_id` INT NOT NULL,
  `facturas_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_vehiculos_titulares1_idx` (`titulares_id` ASC),
  INDEX `fk_contratos_modelos1_idx` (`modelos_id` ASC),
  INDEX `fk_contratos_usoVehiculo1_idx` (`usoVehiculo_id` ASC),
  INDEX `fk_contratos_statusCont1_idx` (`statusCont_id` ASC),
  INDEX `fk_contratos_trans1_idx` (`trans_id` ASC),
  INDEX `fk_contratos_precios1_idx` (`precios_id` ASC),
  INDEX `fk_contratos_tpPago1_idx` (`tpPago_id` ASC),
  INDEX `fk_contratos_planillas1_idx` (`planillas_id` ASC),
  CONSTRAINT `fk_vehiculos_titulares1`
    FOREIGN KEY (`titulares_id`)
    REFERENCES `rcv_db`.`titulares` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contratos_modelos1`
    FOREIGN KEY (`modelos_id`)
    REFERENCES `rcv_db`.`modelos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contratos_usoVehiculo1`
    FOREIGN KEY (`usoVehiculo_id`)
    REFERENCES `rcv_db`.`usoVehiculo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contratos_statusCont1`
    FOREIGN KEY (`statusCont_id`)
    REFERENCES `rcv_db`.`statusCont` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contratos_trans1`
    FOREIGN KEY (`trans_id`)
    REFERENCES `rcv_db`.`trans` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contratos_precios1`
    FOREIGN KEY (`precios_id`)
    REFERENCES `rcv_db`.`precios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contratos_tpPago1`
    FOREIGN KEY (`tpPago_id`)
    REFERENCES `rcv_db`.`tpPago` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contratos_planillas1`
    FOREIGN KEY (`planillas_id`)
    REFERENCES `rcv_db`.`planillas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rcv_db`.`tipoTelf`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rcv_db`.`tipoTelf` ;

CREATE TABLE IF NOT EXISTS `rcv_db`.`tipoTelf` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tpTelf` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rcv_db`.`telefonos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rcv_db`.`telefonos` ;

CREATE TABLE IF NOT EXISTS `rcv_db`.`telefonos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `numTelf` VARCHAR(45) NOT NULL,
  `titulares_id` INT NOT NULL,
  `tipoTelf_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_telefonos_titulares1_idx` (`titulares_id` ASC),
  INDEX `fk_telefonos_tipoTelf1_idx` (`tipoTelf_id` ASC),
  CONSTRAINT `fk_telefonos_titulares1`
    FOREIGN KEY (`titulares_id`)
    REFERENCES `rcv_db`.`titulares` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_telefonos_tipoTelf1`
    FOREIGN KEY (`tipoTelf_id`)
    REFERENCES `rcv_db`.`tipoTelf` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rcv_db`.`correos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rcv_db`.`correos` ;

CREATE TABLE IF NOT EXISTS `rcv_db`.`correos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `correo` VARCHAR(120) NOT NULL,
  `titulares_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_correos_titulares1_idx` (`titulares_id` ASC),
  CONSTRAINT `fk_correos_titulares1`
    FOREIGN KEY (`titulares_id`)
    REFERENCES `rcv_db`.`titulares` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rcv_db`.`perfil`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rcv_db`.`perfil` ;

CREATE TABLE IF NOT EXISTS `rcv_db`.`perfil` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `perfil` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rcv_db`.`preguntas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rcv_db`.`preguntas` ;

CREATE TABLE IF NOT EXISTS `rcv_db`.`preguntas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pregunta` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rcv_db`.`stUsuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rcv_db`.`stUsuarios` ;

CREATE TABLE IF NOT EXISTS `rcv_db`.`stUsuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rcv_db`.`usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rcv_db`.`usuarios` ;

CREATE TABLE IF NOT EXISTS `rcv_db`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `nick` VARCHAR(45) NOT NULL,
  `clave` VARCHAR(100) NOT NULL,
  `respuesta` VARCHAR(45) NOT NULL,
  `perfil_id` INT NOT NULL,
  `agencias_id` INT NOT NULL,
  `preguntas_id` INT NOT NULL,
  `stUsuarios_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_usuarios_perfil1_idx` (`perfil_id` ASC),
  INDEX `fk_usuarios_agencias1_idx` (`agencias_id` ASC),
  INDEX `fk_usuarios_preguntas1_idx` (`preguntas_id` ASC),
  INDEX `fk_usuarios_stUsuarios1_idx` (`stUsuarios_id` ASC),
  CONSTRAINT `fk_usuarios_perfil1`
    FOREIGN KEY (`perfil_id`)
    REFERENCES `rcv_db`.`perfil` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuarios_agencias1`
    FOREIGN KEY (`agencias_id`)
    REFERENCES `rcv_db`.`agencias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuarios_preguntas1`
    FOREIGN KEY (`preguntas_id`)
    REFERENCES `rcv_db`.`preguntas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuarios_stUsuarios1`
    FOREIGN KEY (`stUsuarios_id`)
    REFERENCES `rcv_db`.`stUsuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rcv_db`.`facturas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rcv_db`.`facturas` ;

CREATE TABLE IF NOT EXISTS `rcv_db`.`facturas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(60) NOT NULL,
  `stFormatos_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_facturas_stFormatos1_idx` (`stFormatos_id` ASC),
  CONSTRAINT `fk_facturas_stFormatos1`
    FOREIGN KEY (`stFormatos_id`)
    REFERENCES `rcv_db`.`stFormatos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rcv_db`.`ftEmitidas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rcv_db`.`ftEmitidas` ;

CREATE TABLE IF NOT EXISTS `rcv_db`.`ftEmitidas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecah_em` DATE NOT NULL,
  `contratos_id` INT NOT NULL,
  `facturas_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ftEmitidas_contratos1_idx` (`contratos_id` ASC),
  INDEX `fk_ftEmitidas_facturas1_idx` (`facturas_id` ASC),
  CONSTRAINT `fk_ftEmitidas_contratos1`
    FOREIGN KEY (`contratos_id`)
    REFERENCES `rcv_db`.`contratos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ftEmitidas_facturas1`
    FOREIGN KEY (`facturas_id`)
    REFERENCES `rcv_db`.`facturas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
