<!-- header -->	    
<div id="main-navbar" class="navbar navbar-inverse" role="navigation">		
		<button type="button" id="main-menu-toggle"><i class="navbar-icon fa fa-bars icon"></i><span class="hide-menu-text">HIDE MENU</span></button>		
		<div class="navbar-inner">		
			<div class="navbar-header">
			
				<!-- Logo -->
				<a href="index.html" class="navbar-brand">
					<div><img alt="Pixel Admin" src="<?php echo PUBLIC_URL;?>img/mm.png"></div>
					<?php echo APP_NAME; ?>
				</a>
				
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#main-navbar-collapse"><i class="navbar-icon fa fa-bars"></i></button>

			</div> <!-- / .navbar-header -->

			<div id="main-navbar-collapse" class="collapse navbar-collapse main-navbar-collapse">
				<div>
				
					<div class="right clearfix">
						<ul class="nav navbar-nav pull-right right-navbar-nav">
							
							<li class="dropdown">
								<a href="pages-blank.html#" class="dropdown-toggle user-menu" data-toggle="dropdown">
									<img src="<?php echo PUBLIC_URL; ?>demo/avatars/1.jpg" alt="">
									<span><?php echo utf8_encode( Session::get('name')." ".Session::get('last_name') ); ?></span>
								</a>
								<ul class="dropdown-menu">
									<li><a href="pages-blank.html#"><span class="label label-warning pull-right">New</span>Profile</a></li>
									<li><a href="pages-blank.html#"><span class="badge badge-primary pull-right">New</span>Account</a></li>
									<li><a href="pages-blank.html#"><i class="dropdown-icon fa fa-cog"></i>&nbsp;&nbsp;Settings</a></li>
									<li class="divider"></li>
									<li><a href="<?php echo BASE_URL; ?>login/close"><i class="dropdown-icon fa fa-power-off"></i>&nbsp;&nbsp;Log Out</a></li>
								</ul>
							</li>
						</ul>
						
					</div>
					
				</div>
			</div> <!-- / #main-navbar-collapse -->
		</div> <!-- / .navbar-inner -->
	</div> <!-- / #main-navbar -->
<!-- end header --> 
