<!-- content -->	
	<div class="page-header">
		
		<div class="row">
			<!-- Page header, center on small screens -->
			<h1 class="col-xs-12 col-sm-4 text-center text-left-sm">
				&nbsp;
				<i class="fa <?php echo $this->icon_fa; ?>"></i>
				&nbsp;
				<?php echo $this->titleHead; ?>
			</h1>

			<div class="col-xs-12 col-sm-8">
				<div class="row">
					<hr class="visible-xs no-grid-gutter-h">
					<!-- "Create project" button, width=auto on desktops -->
					
				</div>
			</div>
		</div>
	</div> <!-- / .page-header -->
	
<!-- end content -->
