<!-- sidebar -->	
<div id="main-menu" role="navigation">
		<div id="main-menu-inner">
			
			<div class="menu-content top" id="menu-content-demo">
				
				<div>
					<div class="text-bg">
						<span class="text-semibold" style="font-size: 15px;"><?php echo Session::get('name').' '.Session::get('last_name');?></span>
					</div>
					<div class="btn-group">
						<a href="pages-blank.html#" class="btn btn-xs btn-primary btn-outline dark">
							<i class="fa fa-user"></i>
						</a>
						<a href="pages-blank.html#" class="btn btn-xs btn-primary btn-outline dark">
							<i class="fa fa-cog"></i>
						</a>
						<a href="<?php echo BASE_URL; ?>login/close" class="btn btn-xs btn-danger btn-outline dark">
							<i class="fa fa-power-off"></i>
						</a>
					</div>
					<!-- <a href="pages-blank.html#" class="close">&times;</a>  -->
				</div>
			</div>
			
			<ul class="navigation">
				<?php if ($_view_params['menu']):?>
				<?php 	for ($i = 0; $i < count($_view_params['menu']); $i++) :?>
					
					<?php if (isset($_view_params['menu'][$i]['sub'])):?>
						<li class="mm-dropdown">
							<a href="<?php echo $_view_params['menu'][$i]['link']; ?>">
								<i class="menu-icon fa <?php echo $_view_params['menu'][$i]['icon']; ?>"></i>
								<span class="mm-text"><?php echo $_view_params['menu'][$i]['title']; ?></span></a>
								<ul>
					<?php 	for ($j = 0; $j < count($_view_params['menu'][$i]['sub']); $j++) :?>						
									<li>
										<a tabindex="-1" href="<?php echo $_view_params['menu'][$i]['sub'][$j]['link']; ?>">
											<i class="menu-icon fa fa-caret-right"></i>
											<span class="mm-text"><?php echo $_view_params['menu'][$i]['sub'][$j]['title']; ?></span>
										</a>
									</li>
					<?php 	endfor;?>
								</ul>
						</li>
					
					<?php else:?>
						<li>
							<a href="<?php echo $_view_params['menu'][$i]['link']; ?>">
								<i class="menu-icon fa <?php echo $_view_params['menu'][$i]['icon']; ?>"></i>
								<span class="mm-text"><?php echo $_view_params['menu'][$i]['title']; ?></span>
							</a>
						</li>
					<?php endif;?>
					
				<?php 	endfor;?>
				<?php endif; ?>
			</ul>
			
			
			<div class="menu-content">
				
			</div>
		</div> <!-- / #main-menu-inner -->
	</div> <!-- / #main-menu -->
<!-- /4. $MAIN_MENU -->


	<div id="content-wrapper">
<!-- end sidebar -->
