<!-- statements -->

<!DOCTYPE html>

<!--[if IE 8]>         <html class="ie8"> <![endif]-->
<!--[if IE 9]>         <html class="ie9 gt-ie8"> <![endif]-->
<!--[if gt IE 9]><!--> <html class="gt-ie8 gt-ie9 not-ie"> <!--<![endif]-->
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<title>Blank - Pages - PixelAdmin</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0">

	<!-- Open Sans font from Google CDN -->
	<link href="<?php echo PUBLIC_URL; ?>fonts/fonts.googleapis.com.css" rel="stylesheet" type="text/css">
	<link href="<?php echo PUBLIC_URL; ?>fonts/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">

	<!-- Pixel Admin's stylesheets -->
	<link href="<?php echo PUBLIC_URL; ?>css/bootstrap.min.css" rel="stylesheet" type="text/css">
	<link href="<?php echo PUBLIC_URL; ?>css/pixel-admin.min.css" rel="stylesheet" type="text/css">
	<link href="<?php echo PUBLIC_URL; ?>css/widgets.min.css" rel="stylesheet" type="text/css">
	<link href="<?php echo PUBLIC_URL; ?>css/pages.min.css" rel="stylesheet" type="text/css">
	<link href="<?php echo PUBLIC_URL; ?>css/rtl.min.css" rel="stylesheet" type="text/css">
	<link href="<?php echo PUBLIC_URL; ?>css/themes.min.css" rel="stylesheet" type="text/css">
	
	<link href="<?php echo PUBLIC_URL; ?>css/custom.css" rel="stylesheet" type="text/css">
	
	<!-- hojas de estilos modulares -->		     
	<?php  if (isset($_view_params['css']) && count($_view_params['css'])): ?>
	<?php  	for ($i = 0; $i < count($_view_params['css']); $i++):  ?>		     
	<script src="<?php echo $_view_params['css'][$i]; ?>"></script>		     
	<?php  	endfor; ?>
	<?php  endif;?>

	<!--[if lt IE 9]>
		<script src="<?php echo PUBLIC_URL; ?>js/ie.min.js"></script>
	<![endif]-->

</head>

<body class="theme-default main-menu-animated mmc">

<script>var init = [];</script>
<!-- Demo script --> <script src="<?php echo PUBLIC_URL; ?>demo/demo.js"></script> <!-- / Demo script -->

<div id="main-wrapper">

<!-- end statements --> 
